name: htmldoc
base: core20
version: 1.9.16
summary: HTML and Markdown conversion utility
description: |
  HTMLDOC is a program that reads HTML and Markdown source files or web pages
  and generates corresponding EPUB, HTML, PostScript, or PDF files with an
  optional table of contents.

#confinement: devmode
confinement: strict

#grade: devel
grade: stable

icon: desktop/htmldoc-128.png

apps:
    htmldoc:
        extensions: [gnome-3-38]
        command: usr/bin/htmldoc
        desktop: usr/share/applications/htmldoc.desktop
        plugs: [desktop, home, network, x11]

parts:
    main:
        plugin: autotools
        autotools-configure-parameters: [--prefix=/usr]
        source: .
        build-packages: [build-essential, pkg-config, libfltk1.3-dev, libgnutls28-dev, libjpeg-turbo8-dev, libpng-dev, zlib1g-dev]
        stage-packages: [libfltk-images1.3, libfltk1.3, libfontconfig1, libfreetype6, libjpeg-turbo8, libpng16-16, libx11-6, libxau6, libxcb1, libxcursor1, libxdmcp6, libxext6, libxfixes3, libxft2, libxinerama1, libxrender1]
